cache:
  apt: true
  directories:
    - ${HOME}/castxml
    - /usr/local
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: PYTHONPATH=/usr/local/lib/python2.7/dist-packages
   
addons:
  apt:
    packages:
      - libboost-all-dev
      - python-dev
      - libode-dev
      - libeigen3-dev
      - freeglut3-dev
      - libassimp-dev

install:
  - if [ ! -e /usr/local/lib/libfcl.so ]; then
        wget -O - https://github.com/danfis/libccd/archive/v2.0.tar.gz | tar zxf - ;
        cd libccd-2.0;
        cmake .;
        sudo make install;
        cd ..;
        wget -O - https://github.com/flexible-collision-library/fcl/archive/0.4.0.tar.gz | tar zxf - ;
        cd fcl-0.4.0;
        cmake .;
        sudo make install;
        cd ..;
    fi;
  - if [ ! -e ${HOME}/castxml ]; then
        wget -O - https://midas3.kitware.com/midas/download/item/318227/castxml-linux.tar.gz | tar zxf - -C ${HOME};
    fi;
  - sudo -H pip -v install https://github.com/gccxml/pygccxml/archive/v1.7.2.tar.gz https://bitbucket.org/ompl/pyplusplus/get/1.6.tar.gz

script:
  # get OMPL subrepository
  - git clone --depth=1 --branch=master git://github.com/ompl/ompl.git

  # Create build directory
  - mkdir -p build
  - cd build

  # Configure
  - cmake -DOMPL_REGISTRATION=OFF -DCMAKE_INSTALL_PREFIX=tmp -DCASTXML:FILEPATH=${HOME}/castxml/bin/castxml ..

  # TIMES OUT BECAUSE IT DOES NOT PRODUCE OUTPUT FOR MORE THAN 10 MINUTES
  # generate python bindings
  - make -j4 update_bindings

  # Build
  - make -j4

  
